name: Make release tag latest

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: NodeJS setup
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - uses: ./.github/actions/publishLatest
        name: Get release tag
        id: getReleaseTag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make dist-tag latest
        if: steps.getReleaseTag.outputs.version
        run: |
          npm dist-tag add ${{ steps.getReleaseTag.outputs.packageName }}@${{ steps.getReleaseTag.outputs.version }} latest
