name: Make release tag latest

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: NodeJS setup
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Setup registry
        run: |
          npm config set registry https://artifactory.infrateam.xyz/artifactory/api/npm/npm/
          npm config set always-auth true
          echo "//artifactory.infrateam.xyz/api/npm/npm/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          echo "//artifactory.infrateam.xyz/artifactory/api/npm/npm/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          npm -v

      - uses: ./.github/actions/publishLatest
        name: Get release tag
        id: getReleaseTag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Make dist-tag latest
        if: steps.getReleaseTag.outputs.version
        run: |
          npm dist-tag add ${{ steps.getReleaseTag.outputs.packageName }}@${{ steps.getReleaseTag.outputs.version }} latest
